services:
    
  Postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgreSql
    restart: always
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
    - ${POSTGRES_PORTS}:5432
    volumes:
    - postgreDb:/var/lib/postgresql/data
  
  PgAdmin:
    image: ${PG_ADMIN_IMAGE}
    container_name: PgAdmin
    restart: always
    depends_on:
      - Postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORTS}:80
    volumes:
      - PgAdmin:/var/lib/pgadmin
      
  Seq:
    image: datalust/seq:latest
    container_name: SEQ
    restart: always
    environment:
    - ACCEPT_EULA=${SEQ_ACCEPT_EULA} 
    ports:
    - ${SEQ_PORT}:5341 
    - ${SEQ_PORT_UI}:80
    volumes:
    - Seq:/data
  
  Redis:
    image: ${REDIS_IMAGE}
    container_name: Redis-Cache
    restart: always
    ports:
      - ${REDIS_PORTS}:6379
    volumes:
      - Cache:/data
    
volumes:
  PgAdmin:
  Seq:    
  postgreDb:
  Cache: