// <auto-generated />
using System;
using MetaBond.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetaBond.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetaBondContext))]
    [Migration("20251009203334_AddMigrationsChatMessageAndMessageReads")]
    partial class AddMigrationsChatMessageAndMessageReads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "pending", "accepted", "blocked" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetaBond.Domain.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PkAdmin");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Direct");

                    b.HasKey("Id")
                        .HasName("PkChats");

                    b.HasIndex("CommunityId");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Communities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommunityCategoryId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PkCommunities");

                    b.HasIndex("CommunityCategoryId");

                    b.ToTable("Communities", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.CommunityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PkCommunityCategories");

                    b.ToTable("CommunityCategories", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.CommunityMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LeftOnUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkCommunityMemberships");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityMemberships", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkEmailConfirmationToken");

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmationTokens", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.EventParticipation", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipationInEventId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "ParticipationInEventId");

                    b.HasIndex("ParticipationInEventId");

                    b.ToTable("EventParticipation", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Events", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommunitiesId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateAndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PkEvents");

                    b.HasIndex("CommunitiesId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateAdt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequesterId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PkFriendship");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendship", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InterestCategoryId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id")
                        .HasName("PkInterest");

                    b.HasIndex("InterestCategoryId");

                    b.ToTable("Interests", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.InterestCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PkInterestCategories");

                    b.ToTable("InterestCategories", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PkMessages");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.MessageRead", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageReads", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkNotifications");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ParticipationInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkParticipationInEvent");

                    b.ToTable("ParticipationInEvent", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Posts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommunitiesId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PkPosts");

                    b.HasIndex("CommunitiesId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ProgressBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunitiesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkProgressBoard");

                    b.HasIndex("CommunitiesId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ProgressBoard", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("ProgressBoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkProgressEntry");

                    b.HasIndex("ProgressBoardId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressEntry", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Rewards", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateAwarded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("PointAwarded")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PkRewards");

                    b.HasIndex("UserId");

                    b.ToTable("Rewards", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id")
                        .HasName("PkRoles");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d290f1ee-6c54-4b01-90e6-d701748f0851"),
                            Description = "Default role for standard users",
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("5a4b8c2f-3d1e-4b6f-a1c2-9f3e2d7a6c1b"),
                            Description = "Administrator with full permissions",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MetaBond.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("RoleId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("StatusUser")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PkUser");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.UserChat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChats", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests", (string)null);
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Chat", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Communities", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Communities", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.CommunityCategory", "CommunityCategory")
                        .WithMany("Communities")
                        .HasForeignKey("CommunityCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCommunityCategoryId");

                    b.Navigation("CommunityCategory");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.CommunityMembership", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Communities", "Community")
                        .WithMany("CommunityMemberships")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCommunityMembershipsCommunityId");

                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("CommunityMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCommunityMembershipsUserId");

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.EmailConfirmationToken", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkEmailConfirmationTokensUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.EventParticipation", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Events", "Event")
                        .WithMany("EventParticipations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkEvent");

                    b.HasOne("MetaBond.Domain.Models.ParticipationInEvent", "ParticipationInEvent")
                        .WithMany("EventParticipations")
                        .HasForeignKey("ParticipationInEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkParticipationInEvent");

                    b.Navigation("Event");

                    b.Navigation("ParticipationInEvent");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Events", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Communities", "Communities")
                        .WithMany("Events")
                        .HasForeignKey("CommunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCommunitiesId");

                    b.Navigation("Communities");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Friendship", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FkAddresseeId");

                    b.HasOne("MetaBond.Domain.Models.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FkRequesterId");

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Interest", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.InterestCategory", "InterestCategory")
                        .WithMany("Interest")
                        .HasForeignKey("InterestCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkInterestCategoryId");

                    b.Navigation("InterestCategory");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Message", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkMessagesChatId");

                    b.HasOne("MetaBond.Domain.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkMessagesSenderId");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.MessageRead", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Message", "Message")
                        .WithMany("MessageReads")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkMessageReadsMessageId");

                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("MessageReads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Notification", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkNotificationsUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Posts", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Communities", "Communities")
                        .WithMany("Posts")
                        .HasForeignKey("CommunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCommunities");

                    b.HasOne("MetaBond.Domain.Models.User", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkPostsCreatedById");

                    b.Navigation("Communities");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ProgressBoard", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Communities", "Communities")
                        .WithOne("ProgressBoard")
                        .HasForeignKey("MetaBond.Domain.Models.ProgressBoard", "CommunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkCommunitiesId");

                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("ProgressBoards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkProgressBoardsUserId");

                    b.Navigation("Communities");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ProgressEntry", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.ProgressBoard", "ProgressBoard")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("ProgressBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkProgressBoardId");

                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkProgressEntriesUserId");

                    b.Navigation("ProgressBoard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Rewards", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("Rewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkRewardsUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.User", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkUserRolesId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.UserChat", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkUserChatsChatId");

                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkUserChatsUserId");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.UserInterest", b =>
                {
                    b.HasOne("MetaBond.Domain.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkInterestId");

                    b.HasOne("MetaBond.Domain.Models.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FkUserInterestsUserId");

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Communities", b =>
                {
                    b.Navigation("CommunityMemberships");

                    b.Navigation("Events");

                    b.Navigation("Posts");

                    b.Navigation("ProgressBoard");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.CommunityCategory", b =>
                {
                    b.Navigation("Communities");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Events", b =>
                {
                    b.Navigation("EventParticipations");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.InterestCategory", b =>
                {
                    b.Navigation("Interest");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Message", b =>
                {
                    b.Navigation("MessageReads");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ParticipationInEvent", b =>
                {
                    b.Navigation("EventParticipations");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.ProgressBoard", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MetaBond.Domain.Models.User", b =>
                {
                    b.Navigation("CommunityMemberships");

                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("Interests");

                    b.Navigation("MessageReads");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("ProgressBoards");

                    b.Navigation("ProgressEntries");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("Rewards");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("UserChats");
                });
#pragma warning restore 612, 618
        }
    }
}
